packages:
  - packages/**/*

catalog:
  '@auth/core': 0.39.0
  '@cloudflare/workers-types': 4.20250614.0
  '@eslint/js': 9.29.0
  '@faker-js/faker': 9.8.0
  '@playwright/test': 1.53.0
  '@sentry/browser': 9.28.0
  '@sentry/sveltekit': 9.19.0
  '@sveltejs/adapter-cloudflare': 7.0.1
  '@sveltejs/kit': 2.21.5
  '@sveltejs/package': 2.3.11
  '@sveltejs/vite-plugin-svelte': 5.1.0
  '@types/autosize': 4.0.3
  '@types/eslint-config-prettier': 6.11.3
  '@types/image-blob-reduce': 4.1.4
  '@types/js-cookie': 3.0.6
  '@types/node': 24.0.3
  autosize: 6.0.1
  date-fns: 4.1.0
  dotenv: 16.5.0
  drizzle-kit: 0.31.1
  drizzle-orm: 0.44.2
  eslint: 9.29.0
  eslint-config-prettier: 10.1.5
  eslint-plugin-svelte: 3.9.2
  fcm-cloudflare-workers: 2.0.1
  firebase: 11.6.0
  image-blob-reduce: 4.1.0
  image-size: 2.0.2
  jdenticon: 3.3.0
  jiti: 2.4.2
  js-cookie: 3.0.5
  js-xxhash: 4.0.0
  linkify-html: 4.3.1
  lru-cache: 11.1.0
  miniflare: 4.20250604.1
  mockdate: 3.0.5
  prettier: 3.5.3
  prettier-plugin-organize-imports: 4.1.0
  prettier-plugin-svelte: 3.4.0
  publint: 0.3.12
  sass: 1.89.2
  svelte: 5.34.3
  svelte-check: 4.2.1
  svelte-eslint-parser: 1.2.0
  the-new-css-reset: 1.11.3
  tsx: 4.19.3
  typesafe-i18n: 5.26.2
  typescript: 5.8.3
  typescript-eslint: 8.34.1
  valibot: 1.0.0
  vite: 6.3.5
  vitest: 3.2.3
  workbox-precaching: 7.3.0
  workbox-routing: 7.3.0
  workbox-strategies: 7.3.0
