runs:
  using: 'composite'
  steps:
    - uses: pnpm/action-setup@v3
      with:
        version: 10.12.4

    - uses: actions/setup-node@v4
      with:
        node-version: '24.3.0'
        cache: 'pnpm'

    - run: |
        pnpm install --frozen-lockfile
      shell: bash
