// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'en'

export type Locales =
	| 'en'
	| 'ja'

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
	/**
	 * E​d​i​t
	 */
	edit: string
	/**
	 * C​a​n​c​e​l
	 */
	cancel: string
	/**
	 * B​a​c​k
	 */
	back: string
	/**
	 * P​r​e​v​i​e​w
	 */
	preview: string
	/**
	 * S​e​t​t​i​n​g​s
	 */
	settings: string
	/**
	 * (​R​e​q​u​i​r​e​d​)
	 */
	required: string
	/**
	 * T​i​t​l​e
	 */
	title: string
	/**
	 * D​e​s​c​r​i​p​t​i​o​n
	 */
	desc: string
	/**
	 * S​e​l​e​c​t​ ​i​c​o​n
	 */
	selectIcon: string
	/**
	 * R​e​m​o​v​e
	 */
	removeIcon: string
	/**
	 * Y​o​u​r​ ​i​n​p​u​t​ ​e​x​c​e​e​d​s​ ​t​h​e​ ​c​h​a​r​a​c​t​e​r​ ​l​i​m​i​t​.
	 */
	textTooLong: string
	/**
	 * N​o​ ​a​n​n​o​u​n​c​e​m​e​n​t​s​ ​y​e​t​.
	 */
	noAnnouncements: string
	/**
	 * C​r​e​a​t​e​ ​C​h​a​n​n​e​l
	 */
	createChannel: string
}

export type TranslationFunctions = {
	/**
	 * Edit
	 */
	edit: () => LocalizedString
	/**
	 * Cancel
	 */
	cancel: () => LocalizedString
	/**
	 * Back
	 */
	back: () => LocalizedString
	/**
	 * Preview
	 */
	preview: () => LocalizedString
	/**
	 * Settings
	 */
	settings: () => LocalizedString
	/**
	 * (Required)
	 */
	required: () => LocalizedString
	/**
	 * Title
	 */
	title: () => LocalizedString
	/**
	 * Description
	 */
	desc: () => LocalizedString
	/**
	 * Select icon
	 */
	selectIcon: () => LocalizedString
	/**
	 * Remove
	 */
	removeIcon: () => LocalizedString
	/**
	 * Your input exceeds the character limit.
	 */
	textTooLong: () => LocalizedString
	/**
	 * No announcements yet.
	 */
	noAnnouncements: () => LocalizedString
	/**
	 * Create Channel
	 */
	createChannel: () => LocalizedString
}

export type Formatters = {}
