export const USER_ID_MAX_BYTES = 256;
export const CHANNEL_ID_MAX_BYTES = 8;

export const CHANNEL_NAME_MAX_BYTES = 150;
export const CHANNEL_DESC_MAX_BYTES = 1000;
export const CHANNEL_ICON_MAX_SIZE = 256;
export const CHANNEL_ICON_MAX_BYTES = 1000000;

export const ANNOUNCEMENT_ID_LENGTH = 10;
export const ANNOUNCEMENT_TITLE_MAX_BYTES = 200;
export const ANNOUNCEMENT_BODY_MAX_BYTES = 2000;
export const ANNOUNCEMENT_IMAGE_MAX_SIZE = 1200;
export const ANNOUNCEMENT_IMAGE_MAX_BYTES = 2000000;

export const STORAGE_ID_MAX_BYTES = 100;
