export const CHANNEL_NAME_MAX_BYTES = 150;
export const CHANNEL_DESC_MAX_BYTES = 1000;
export const CHANNEL_ICON_MAX_SIZE = 256;
export const CHANNEL_ICON_MAX_BYTES = 1024 * 256;
export const ANNOUNCEMENT_TITLE_MAX_BYTES = 200;
export const ANNOUNCEMENT_BODY_MAX_BYTES = 2000;
export const ANNOUNCEMENT_HEADER_IMAGE_MAX_SIZE = 1200;
