name: check

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/workflows/setup

      - run: pnpm run check

  playwright-components:
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright:v1.46.0-jammy
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/workflows/setup

      - run: pnpm run sync
        working-directory: ./packages/components

      - run: pnpm run playwright
        working-directory: ./packages/components
