on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v3
        with:
          version: 8.15.0

      - uses: actions/setup-node@v4
        with:
          node-version: '20.9.0'
          cache: 'pnpm'

      - run: pnpm install --frozen-lockfile

      - run: pnpm run check
