name: deploy

on:
  push:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    environment: live

    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/workflows/setup

      - run: |
          echo pnpm run build
          echo pnpm run migrate
          echo pnpm run deploy
