name: deploy

on:
  push:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    environment: live

    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/workflows/setup
        if: false

      - run: |
          yq -V
          echo ${VALUES_YAML} >> values.yaml
          cat values.yaml
          echo === try 1 ===
          yq '.' values.yaml
          echo === try 2 ===
          yq '.[]' values.yaml
          echo === try 3 ===
          yq '.[] | "\(key)"' values.yaml
        env:
          VALUES_YAML: ${{ vars.VALUES_YAML }}

      - run: echo WRITER_PROJECT_NAME = [${WRITER_PROJECT_NAME}]

      - run: |
          echo pnpm run build
          echo pnpm run migrate
          echo pnpm run deploy
