on:
  workflow_dispatch:

jobs:
  snapshot:
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright:v1.46.0-jammy
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v3
        with:
          version: 9.6.0

      - uses: actions/setup-node@v4
        with:
          node-version: '20.16.0'
          cache: 'pnpm'

      - run: pnpm install --frozen-lockfile

      - run: pnpm run build

      - run: pnpm run playwright --update-snapshots
        working-directory: ./packages/components
        env:
          HOME: /root

      - uses: actions-js/push@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          message: 'Update snapshot'
