on:
  workflow_dispatch:

jobs:
  snapshot:
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright:v1.46.0-jammy
    timeout-minutes: 10
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v3
        with:
          version: 9.6.0

      - uses: actions/setup-node@v4
        with:
          node-version: '20.16.0'
          cache: 'pnpm'

      - run: pnpm install --frozen-lockfile

      - run: pnpm run build
        working-directory: ./packages/components

      - run: pnpm run playwright --update-snapshots --project=chromium
        working-directory: ./packages/components
        env:
          HOME: /root

      - run: git config --global --add safe.directory $PWD

      - id: diff
        run: |
          git add -N .
          git diff --name-only --exit-code
        continue-on-error: true
      - run: |
          set -x
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
          git add .
          git commit -m 'Update snapshots'
          git push
        if: steps.diff.outcome == 'failure'
