name: snapshots/components

on:
  workflow_dispatch:

jobs:
  snapshot:
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright:v1.46.0-jammy
    timeout-minutes: 10
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/workflows/setup

      - run: pnpm run sync
        working-directory: ./packages/components

      - uses: ./.github/workflows/snapshots
        with:
          target: components
