name: snapshots/reader

on:
  push:
  workflow_dispatch:

jobs:
  snapshot:
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright:v1.46.0-jammy
    timeout-minutes: 10
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/workflows/setup

      - run: pnpm run build
        working-directory: ./packages/components

      - run: pnpm run build
        working-directory: ./packages/db

      - run: pnpm tsx tools/genTestData.ts
        working-directory: ./packages/db

      - uses: ./.github/workflows/reader
        with:
          target: components
