name: update-snapshots

on:
  workflow_dispatch:
    inputs:
      components:
        type: boolean
        default: true
      reader:
        type: boolean
        default: true
      writer:
        type: boolean
        default: true

jobs:
  # https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/using-a-matrix-for-your-jobs#example-using-an-output-to-define-two-matrices
  define-matrix:
    runs-on: ubuntu-latest
    outputs:
      targets: ${{ steps.targets.outputs.targets }}
    steps:
      - id: targets
        run: |
          A=()

          if [ "${{ github.event.inputs.components }}" = "true" ]; then
            A+=('"components"')
          fi

          if [ "${{ github.event.inputs.reader }}" = "true" ]; then
            A+=('"reader"')
          fi

          if [ "${{ github.event.inputs.writer }}" = "true" ]; then
            A+=('"writer"')
          fi

          echo "targets=[$(IFS=,; echo "${A[*]}")]" >> "$GITHUB_OUTPUT"

  update-snapshorts:
    needs: define-matrix
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target: ${{ fromJson(needs.define-matrix.outputs.targets) }}
    steps:
      - run: echo "Running ${{ matrix.target }} job"
