name: update-snapshots

on:
  workflow_dispatch:
    inputs:
      components:
        type: boolean
        default: false
      reader:
        type: boolean
        default: false
      writer:
        type: boolean
        default: false

jobs:
  generate-matrix:
    runs-on: ubuntu-latest
    outputs:
      targets: ${{ steps.gen.outputs.targets }}
    steps:
      - id: gen
        run: |
          A=()

          if [ "${{ github.event.inputs.components }}" = "true" ]; then
            A+=("components")
          fi

          if [ "${{ github.event.inputs.reader }}" = "true" ]; then
            A+=("reader")
          fi

          if [ "${{ github.event.inputs.writer }}" = "true" ]; then
            A+=("writer")
          fi

          echo "targets=[$(IFS=,; echo "${A[*]}")]" >> "$GITHUB_OUTPUT"

  update-snapshorts:
    needs: generate-matrix
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target: ${{ fromJson(needs.generate-matrix.outputs.targets) }}
    steps:
      - run: echo "Running ${{ matrix.target }} job"
