name: update-snapshots

on:
  workflow_dispatch:
    inputs:
      components:
        type: boolean
        default: true
      reader:
        type: boolean
        default: true
      writer:
        type: boolean
        default: true

jobs:
  generate-matrix:
    runs-on: ubuntu-latest
    outputs:
      targets: ${{ steps.targets.outputs.targets }}
    steps:
      - id: targets
        run: |
          A=()

          if [ "${{ github.event.inputs.components }}" = "true" ]; then
            A+=("components")
          fi

          if [ "${{ github.event.inputs.reader }}" = "true" ]; then
            A+=("reader")
          fi

          if [ "${{ github.event.inputs.writer }}" = "true" ]; then
            A+=("writer")
          fi

          echo "targets=[$(IFS=,; echo "${A[*]}")]" >> "$GITHUB_OUTPUT"

  update-snapshorts:
    needs: generate-matrix
    runs-on: ubuntu-latest
    #    strategy:
    #      matrix:
    #        target: ${{ fromJson(needs.generate-matrix.outputs.targets) }}
    steps:
      - run: echo ${{ needs.generate-matrix.outputs.targets }}
#      - run: echo "Running ${{ matrix.target }} job"
